// <auto-generated />
namespace EF.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PersonalAccountNote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonalAccountNote));
        
        string IMigrationMetadata.Id
        {
            get { return "201712302357592_PersonalAccountNote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
